// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'secrets.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: firebaseWebApiKey,
    appId: '1:37404708646:web:8a9ca3874c71c70b063be7',
    messagingSenderId: '37404708646',
    projectId: 'celsiuslink-bea40',
    authDomain: 'celsiuslink-bea40.firebaseapp.com',
    databaseURL:
        'https://celsiuslink-bea40-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'celsiuslink-bea40.appspot.com',
    measurementId: 'G-SWGT7V34V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: firebaseAndroidApiKey,
    appId: '1:37404708646:android:ba9b4e1a54e2a9ae063be7',
    messagingSenderId: '37404708646',
    projectId: 'celsiuslink-bea40',
    databaseURL:
        'https://celsiuslink-bea40-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'celsiuslink-bea40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: firebaseIOSApiKey,
    appId: '1:37404708646:ios:6a8d3068d41107a5063be7',
    messagingSenderId: '37404708646',
    projectId: 'celsiuslink-bea40',
    databaseURL:
        'https://celsiuslink-bea40-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'celsiuslink-bea40.appspot.com',
    iosClientId:
        '37404708646-g8ha2pln56f1a11usnbe9im368n75civ.apps.googleusercontent.com',
    iosBundleId: 'com.example.celsiusLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: firebaseMcOSApiKey,
    appId: '1:37404708646:ios:c3a84177d3491849063be7',
    messagingSenderId: '37404708646',
    projectId: 'celsiuslink-bea40',
    databaseURL:
        'https://celsiuslink-bea40-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'celsiuslink-bea40.appspot.com',
    iosClientId:
        '37404708646-klcfnuj06842p2tpbl9ndqbjrjk17ilf.apps.googleusercontent.com',
    iosBundleId: 'com.example.celsiusLink.RunnerTests',
  );
}
