name: celsius_link
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-134.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.0.1
  riverpod: ^2.3.6
  freezed: ^2.0.2
  freezed_annotation: ^2.0.1
  flutter_riverpod: ^2.3.6
  firebase_core: ^2.15.0
  firebase_database: ^10.2.2
  firebase_auth: ^4.6.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.10
  

flutter:
  uses-material-design: true
